#FileUpdated
#Tue Jun 24 21:33:44 IST 2025
MSG=User Added Successfully. You can not see added user.
password=123456
url=file\:///E\:/Selenium/OfflineWebsiteForSelenium/OfflineWebsite/pages/examples/login.html
username=kiran@gmail.com